package com.company.superme198.HashTable;

public class FindTheDifferent {


    /**Link:https://leetcode.com/problems/find-the-difference/description/
     * Given two strings s and t which consist of only lowercase letters.
     *String t is generated by random shuffling string s and then add one more letter at a random position.
     *Find the letter that was added in t.
     *Example:
     *Input:
     *s = "abcd"
     *t = "abcde"
     *Output:
     *e
     *Explanation:
     *'e' is the letter that was added.*/
    static  char findTheDifference(String s, String t) {
        int[] arr = new int[26];
        int[] arr1 = new int[26];
        for(int i =0, j= 0; i < s.length() || j < t.length(); i++, j++){
            if(i < s.length())
                arr1[s.charAt(i) - 'a']++;
            if(j < t.length())
                arr[t.charAt(j) - 'a']++;
        }
        for(int i =0;i<26;i++){
            if(arr[i] != arr1[i])
                return (char)(i+'a');
        }
        return ' ';
    }
}
